### ISSUE TITLE
Not work in UE4.23

### ISSUE THREAD

**Issue by AngelTs** [calben/UnrealVictoryUmgPlugin#2]
Not work in UE4.23
1>E:\UE4\Engine\Plugins\Runtime\VictoryUMG\Source\VictoryUMG\Private\JoyColorWheel.cpp(1): error : Expected JoyColorWheel.h to be first header included.
1>e:\ue4\engine\plugins\runtime\victoryumg\source\victoryumg\public\SJoyColorPicker.h(14): fatal error C1083: Cannot open include file: 'SColorPicker.h': No such file or directory

**Comment by TRI99ERED** [comment]
Does it work in 4.21?

**Comment by CommanderPho** [comment]
I updated the plugin to work in UE 4.24, and I suspect that my changes would fix the issues with these older versions of the engine as well.

Hopefully the pull-request gets integrated soon, but if it doesn't feel free to clone my fork at https://github.com/CommanderPho/UnrealVictoryUmgPlugin
to get a version that works with the modern engine.
